//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public int Id { get; set; }
        public string GoodsName { get; set; }
        public decimal GoodsPrice { get; set; }
        public int GoodsCount { get; set; }
        public string GoodsImage { get; set; }

        public string GetPrice => Convert.ToString(this.GoodsPrice) + " руб.";
        public string GetCount => "В количестве " + Convert.ToString(this.GoodsCount) + " шт.";
    }
}
